# Generated by Django 5.0.3 on 2024-03-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
